#ifndef HANGEWUBI_H
#define HANGEWUBI_H

/* 本文件由 cbindgen 从 src/ffi.rs 自动生成，请勿手动编辑。 */
/* This file is auto-generated by cbindgen from src/ffi.rs. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// FFI 返回的动作类型
typedef enum FfiAction {
  // 提交文本
  FFI_ACTION_COMMIT = 0,
  // 更新候选列表
  FFI_ACTION_UPDATE_CANDIDATES = 1,
  // 重置
  FFI_ACTION_RESET = 2,
  // 未处理
  FFI_ACTION_UNHANDLED = 3,
} FfiAction;

// FFI 返回结果
typedef struct FfiResult {
  enum FfiAction action;
  // 提交的文本（需要调用 ffi_free_string 释放）
  char *text;
} FfiResult;

// 候选词信息
typedef struct FfiCandidate {
  char *text;
  char *code;
  bool is_user;
} FfiCandidate;

// 候选列表
typedef struct FfiCandidateList {
  struct FfiCandidate *candidates;
  size_t count;
} FfiCandidateList;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// 初始化引擎
// dict_path: 码表文件路径（UTF-8 C 字符串）
// 返回加载的词条数，失败返回 -1
int64_t ffi_init(const char *dict_path);

// 初始化引擎（支持拼音混输）
// dict_path: 五笔码表路径
// pinyin_dict_path: 拼音词典路径（可为 null）
// 返回加载的词条数，失败返回 -1
int64_t ffi_init_with_pinyin(const char *dict_path, const char *pinyin_dict_path);

// 处理字母按键
struct FfiResult ffi_handle_key(char key);

// 处理空格键
struct FfiResult ffi_handle_space(void);

// 处理数字键 (1-9)
struct FfiResult ffi_handle_number(uint8_t num);

// 处理退格键
struct FfiResult ffi_handle_backspace(void);

// 处理 Escape 键
struct FfiResult ffi_handle_escape(void);

// 处理 Enter 键
struct FfiResult ffi_handle_enter(void);

// 处理标点符号
struct FfiResult ffi_handle_punctuation(char ch);

// 处理分号键
struct FfiResult ffi_handle_semicolon(void);

// 处理单引号键（选第三候选）
struct FfiResult ffi_handle_quote(void);

// 下一页
struct FfiResult ffi_next_page(void);

// 上一页
struct FfiResult ffi_prev_page(void);

// 切换中英文模式
void ffi_toggle_mode(void);

// 获取当前输入模式
// 0=中文, 1=英文, 2=临时英文
uint8_t ffi_get_mode(void);

// 获取当前编码缓冲区
// 返回的字符串需要调用 ffi_free_string 释放
char *ffi_get_buffer(void);

// 获取候选列表
// 返回的列表需要调用 ffi_free_candidate_list 释放
struct FfiCandidateList ffi_get_candidates(void);

// 释放 FFI 返回的字符串
void ffi_free_string(char *s);

// 释放候选列表
void ffi_free_candidate_list(struct FfiCandidateList list);

// 更新引擎配置
void ffi_set_config(bool auto_commit_unique_4,
                    bool auto_commit_first_5,
                    uint8_t enter_key_action,
                    uint8_t empty_code_action,
                    uint8_t candidate_count,
                    bool pinyin_mixed_enabled);

// 添加用户词条
void ffi_add_user_word(const char *code, const char *text);

// 保存用户词典
bool ffi_save_user_dict(const char *path);

// 从磁盘加载用户词典到引擎（启动时调用）
// path: 用户词典 JSON 文件路径（与 ffi_save_user_dict 使用同一路径）
// 文件不存在或解析失败时退化为空词典；引擎已初始化且 path 非空返回 true。
bool ffi_load_user_dict(const char *path);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HANGEWUBI_H */
